'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Restaurant_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5_Minute_Buffalo_Chicken_Wraps__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5 Minute Buffalo Chicken Wraps (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Blueberry_Cupcakes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blueberry Cupcakes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Blueberry_Cupcakes1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blueberry Cupcakes1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Café_Pista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Café Pista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COLOR_MEETS_ELEGANCE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COLOR MEETS ELEGANCE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CRAVE_on_Twitter__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CRAVE on Twitter (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Easy_Saucy_Ramen_Noodles__Vegan_Recipe___1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Easy Saucy Ramen Noodles (Vegan Recipe) (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gülmen_Interiors_presents__Istanbul_Coffee_Shop___Store() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gülmen Interiors presents_ Istanbul Coffee Shop & Store", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gülmen_Interiors_presents__Istanbul_Coffee_Shop___Store1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gülmen Interiors presents_ Istanbul Coffee Shop & Store1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gülmen_Interiors_presents__Istanbul_Coffee_Shop___Store2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gülmen Interiors presents_ Istanbul Coffee Shop & Store2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hazelnut_pistachio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hazelnut pistachio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_1564520_code_open_password_icon_64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_1564520_code_open_password_icon_64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_2024644_login_user_avatar_person_users_icon_512px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_2024644_login_user_avatar_person_users_icon_512px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_2024644_login_user_avatar_person_users_icon_64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_2024644_login_user_avatar_person_users_icon_64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Korean_Corn_Dogs__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Korean Corn Dogs (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KUEY_TEOW_GORENG_CHINESE_STYLE__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KUEY TEOW GORENG CHINESE STYLE (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KUEY_TEOW_GORENG_CHINESE_STYLE__1___1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KUEY TEOW GORENG CHINESE STYLE (1) (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nudefish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nudefish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Oven_Fried_Cajun_Popcorn_Chicken_with_Creamy_Honey_Mustard___1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Oven Fried Cajun Popcorn Chicken with Creamy Honey Mustard_ (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RESEP_MANTAN__ANEKA_RESEP_NASI_GORENG_KHAS_INDONESIA_YANG_LEZAT__PRAKTIS_DAN_EKONOMIS__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RESEP MANTAN_ ANEKA RESEP NASI GORENG KHAS INDONESIA YANG LEZAT, PRAKTIS DAN EKON"& _ 
                        "OMIS (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RESEP_MANTAN__ANEKA_RESEP_NASI_GORENG_KHAS_INDONESIA_YANG_LEZAT__PRAKTIS_DAN_EKONOMIS__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RESEP MANTAN_ ANEKA RESEP NASI GORENG KHAS INDONESIA YANG LEZAT, PRAKTIS DAN EKON"& _ 
                        "OMIS (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RESEP_MANTAN__ANEKA_RESEP_NASI_GORENG_KHAS_INDONESIA_YANG_LEZAT__PRAKTIS_DAN_EKONOMIS__2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RESEP MANTAN_ ANEKA RESEP NASI GORENG KHAS INDONESIA YANG LEZAT, PRAKTIS DAN EKON"& _ 
                        "OMIS (2)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Snacking__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Snacking (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Strawberry_Cupcakes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Strawberry Cupcakes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VENDIDA_A_UN_NARCO__IMAGINA_CON_JUNGKOOK_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VENDIDA A UN NARCO {IMAGINA CON JUNGKOOK}", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_s_Hot_on_Pinterest__7_Bohemian_Interior_Design_Ideas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What's Hot on Pinterest_ 7 Bohemian Interior Design Ideas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property เพลินไปกับความคิวท์ของคาเฟ่สีชมพูสาขาใหม่ที่_House_Of_Eden_at_Siam_Discovery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("เพลินไปกับความคิวท์ของคาเฟ่สีชมพูสาขาใหม่ที่ House Of Eden at Siam Discovery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property เพลินไปกับความคิวท์ของคาเฟ่สีชมพูสาขาใหม่ที่_House_Of_Eden_at_Siam_Discovery__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("เพลินไปกับความคิวท์ของคาเฟ่สีชมพูสาขาใหม่ที่ House Of Eden at Siam Discovery (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
